daktary:
  meta:
    title: 'Daktary: A dead simple kind of blog'
    description: 'For writers who want a very simple tool for writing and publishing her numerics contents, Daktary unlike to wordpress help us to keep focus and to present a readable contents for readers.'

  ghRepos:
  - label: pages pratiques
    account: multibao
    repo: contributions
    folder: pages

  - label: fiches multibao
    account: multibao
    repo: contributions
    folder: contributions

  - label: réseau transition
    account: reseautransitionwb
    repo: reseau_transition
    folder: contributions

  - label: démocratie ouverte
    account: alecoz
    repo: democratie_ouverte
    folder: contributions
  
  ghCss:
    contrib: contribs.css

prose:
  rooturl: 'contributions'
  media: 'media'
  metadata:
    contributions:
      - name: "author"
        field:
          element: "text"
          label: "Author"
          value: "author"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "description"
        field:
          element: "textarea"
          label: "Description"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Agile"
              value: "agile"
            - name: "Collaboratif"
              value: "collaboratif"
            - name: "Scopyleft"
              value: "scopyleft"
            - name: "Meteor"
              value: "meteor"
            - name: "Lean"
              value: "lean"
