daktary:
  home: /pointbar/daktary/examples
  meta:
    title: 'Blog de .|'
    description: 'Blog personnel'

  ghRepos:
  - label: daktary-contribs
    account: daktary
    repo: contribs
    folder: examples

  - label: multibao
    account: multibao
    repo: contributions
    folder: contributions

  - label: Les traducteurs agiles
    account: les-traducteurs-agiles
    repo: les-traducteurs-agiles.github.io
    folder: _posts

  dkCss: assets/css/daktary.css
  dkImgPath: assets/img
  
prose:
  rooturl: 'examples'
  media: 'media'
  metadata:
    contributions:
      - name: "author"
        field:
          element: "text"
          label: "Author"
          value: "author"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "description"
        field:
          element: "textarea"
          label: "Description"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Agile"
              value: "agile"
            - name: "Collaboratif"
              value: "collaboratif"
            - name: "Scopyleft"
              value: "scopyleft"
            - name: "Meteor"
              value: "meteor"
            - name: "Lean"
              value: "lean"
